sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - redis-server
install: true
# The environment variable ${TRAVIS_PULL_REQUEST} is set to "false" when the build 
# is for a normal branch commit. When the build is for a pull request, it will 
# contain the pull requestâ€™s number.
script:
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./mvnw -s .settings.xml package -U -Dmaven.test.redirectTestOutputToFile=false'
